name: designthinking
favicon: null
layout_spectrum: 0.56845
typography_spectrum: 0.78881
title: Design Thinking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#bed856'
    - '#000000'
    - '#e91e76'
    - '#555555'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
