typography_spectrum: 0.84551104856655
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.5294297270011157
  lightness: 0.6561906703282148
  saturation: 0.23268809518776834
  rhythmicContrast: 0.42391107487492263
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7307022609747946
analytics:
  google: null
  facebook: null
  twitter: null
name: designthinking
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 9aa2c2fa-32e0-4907-82cc-da8713001c59
    url: 2016-06-08-design-thinking-comes-of-age.html
    name: Design Thinking Comes of Age
    type: content
favicon: null
title: Design Thinking
purpose: []
